
server:
  port: 8080

spring:
  application:
    name: 'loja'

feign.client.config.default.connectTimeout: 160000000
feign.client.config.default.readTimeout: 160000000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka